//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Massive.Interview.ViewerApp.Remote {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Remote.IGraphService")]
    public interface IGraphService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphService/GetGraph", ReplyAction="http://tempuri.org/IGraphService/GetGraphResponse")]
        Massive.Interview.Service.GraphData GetGraph();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphService/GetGraph", ReplyAction="http://tempuri.org/IGraphService/GetGraphResponse")]
        System.Threading.Tasks.Task<Massive.Interview.Service.GraphData> GetGraphAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraphServiceChannel : Massive.Interview.ViewerApp.Remote.IGraphService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraphServiceClient : System.ServiceModel.ClientBase<Massive.Interview.ViewerApp.Remote.IGraphService>, Massive.Interview.ViewerApp.Remote.IGraphService {
        
        public GraphServiceClient() {
        }
        
        public GraphServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraphServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Massive.Interview.Service.GraphData GetGraph() {
            return base.Channel.GetGraph();
        }
        
        public System.Threading.Tasks.Task<Massive.Interview.Service.GraphData> GetGraphAsync() {
            return base.Channel.GetGraphAsync();
        }
    }
}
