// <auto-generated />
using Massive.Interview.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Massive.Interview.Entities.Migrations
{
    [DbContext(typeof(GraphEntities))]
    partial class GraphEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Massive.Interview.Entities.AdjacentNode", b =>
                {
                    b.Property<long?>("LeftNodeId");

                    b.Property<long?>("RightNodeId");

                    b.HasKey("LeftNodeId", "RightNodeId");

                    b.HasIndex("LeftNodeId");

                    b.HasIndex("RightNodeId");

                    b.ToTable("AdjacentNodes");
                });

            modelBuilder.Entity("Massive.Interview.Entities.Node", b =>
                {
                    b.Property<long?>("NodeId");

                    b.Property<string>("Label");

                    b.HasKey("NodeId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Massive.Interview.Entities.AdjacentNode", b =>
                {
                    b.HasOne("Massive.Interview.Entities.Node", "LeftNode")
                        .WithMany("RightAdjacentNodes")
                        .HasForeignKey("LeftNodeId");

                    b.HasOne("Massive.Interview.Entities.Node", "RightNode")
                        .WithMany("LeftAdjacentNodes")
                        .HasForeignKey("RightNodeId");
                });
#pragma warning restore 612, 618
        }
    }
}
