//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Massive.Interview.LoaderApp.Remote {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Remote.ILoaderService")]
    internal interface ILoaderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaderService/GetExistingNodeIds", ReplyAction="http://tempuri.org/ILoaderService/GetExistingNodeIdsResponse")]
        System.Collections.Generic.List<long> GetExistingNodeIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaderService/GetExistingNodeIds", ReplyAction="http://tempuri.org/ILoaderService/GetExistingNodeIdsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<long>> GetExistingNodeIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaderService/LoadNodes", ReplyAction="http://tempuri.org/ILoaderService/LoadNodesResponse")]
        void LoadNodes(System.Collections.Generic.List<Massive.Interview.Service.Contract.NodeInputData> nodeinputs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaderService/LoadNodes", ReplyAction="http://tempuri.org/ILoaderService/LoadNodesResponse")]
        System.Threading.Tasks.Task LoadNodesAsync(System.Collections.Generic.List<Massive.Interview.Service.Contract.NodeInputData> nodeinputs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ILoaderServiceChannel : Massive.Interview.LoaderApp.Remote.ILoaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class LoaderServiceClient : System.ServiceModel.ClientBase<Massive.Interview.LoaderApp.Remote.ILoaderService>, Massive.Interview.LoaderApp.Remote.ILoaderService {
        
        public LoaderServiceClient() {
        }
        
        public LoaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<long> GetExistingNodeIds() {
            return base.Channel.GetExistingNodeIds();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<long>> GetExistingNodeIdsAsync() {
            return base.Channel.GetExistingNodeIdsAsync();
        }
        
        public void LoadNodes(System.Collections.Generic.List<Massive.Interview.Service.Contract.NodeInputData> nodeinputs) {
            base.Channel.LoadNodes(nodeinputs);
        }
        
        public System.Threading.Tasks.Task LoadNodesAsync(System.Collections.Generic.List<Massive.Interview.Service.Contract.NodeInputData> nodeinputs) {
            return base.Channel.LoadNodesAsync(nodeinputs);
        }
    }
}
